org: prasanvb
app: serverless
service: express-api-project-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
