# Commented the app and org Settings to disable Serverless Framework Observability
# org: prasanvb
# app: serverless
service: serverless-dynamodb

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: 'dev'
  region: 'us-west-2'
  memorySize: 512
  # default timeout of the API gateway is 30 sec
  timeout: 30
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
  # Mitigate Error: CREATE_FAILED: CustomApiGatewayAccountCloudWatchRole (Custom::ApiGatewayAccountRole)
  logs:
    restApi: 
      accessLogging: false
      executionLogging: false

functions:
  # url: https://g07wtfh8a7.execute-api.us-west-2.amazonaws.com/dev/user
  createUser:
    handler: functions/user/handler.createUser
    description: "Create a new user"
    events:
      - http:
          path: user
          method: post
          cors: true
    role: customRole
  # https://g07wtfh8a7.execute-api.us-west-2.amazonaws.com/dev/user/prasan@gmail.com
  getUser:
    handler: functions/user/handler.getUser
    description: "Get user by email"
    events:
      - http:
          path: user/{email}
          method: get
          cors: true
    role: customRole
  queryUsers:
    handler: functions/user/handler.queryUsers
    description: "Query user table"
    events:
      - http:
          path: user/query
          method: post
          cors: true
    role: customRole

plugins:
  - serverless-offline

custom:
  usersTableName: usersTable-${opt:stage, self:provider.stage}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: country
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 10
        GlobalSecondaryIndexes:
          - IndexName: createdAtIndex
            KeySchema:
              - AttributeName: country
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 10    
    customRole: 
      Type: "AWS::IAM::Role"
      Properties:
        Path: "/"
        RoleName: "LambdaDynamoDBFullAccessRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "LambdaDynamoDBFullAccess"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"                    
                  Resource: 
                    # arn:aws:logs:us-west-2:980921714626:log-group:/aws/lambda/*:*:*
                    - "Fn::Join":
                      - ":"
                      - 
                        - "arn:aws:logs"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "dynamodb:*"  
                    - "dynamodb:ListTables"
                    - "dynamodb:PutItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:Query"
                  Resource: 
                  # Allow querying the base table and the GSI
                  # arn:aws:dynamodb:us-west-2:123456789012:table/YourTableName/index/YourGSIName
                    - "arn:aws:dynamodb:*:*:table/*"
                    - "arn:aws:dynamodb:*:*:table/*/index/*"
        
